"use client";

import { useState } from "react";
import { Search, SlidersHorizontal, X } from "lucide-react";
import { REPORT_TYPE_LABELS } from "@/lib/constants";
import {
  REPORT_SORT_OPTIONS,
  REPORT_AUDIENCE_OPTIONS,
  REPORT_STATUS_OPTIONS,
  REPORT_SCOPE_OPTIONS,
  hasActiveReportFilters,
  type ReportFilterState,
} from "@/lib/reportSearch";
import { BTN_TERTIARY, CARD, CHIP, INPUT, INPUT_STYLE } from "@/lib/ui";

// The controls above Report History. Fully controlled — it owns no state, so
// the same bar drives the practitioner history and the athlete's My Reports,
// which need different subsets of it.
//
// `show` turns off the controls a surface has no use for rather than forcing
// each caller to reimplement the bar. On My Reports, "audience", "status" and
// "scope" are all meaningless: an athlete only ever sees reports someone
// deliberately shared with them, so every row would be shared/official and none
// of them was generated by the reader.

export interface ReportFilterBarProps {
  value: ReportFilterState;
  onChange: (next: ReportFilterState) => void;
  /** Types present in the underlying data, so the chips only offer filters that
   *  can actually match something. */
  availableTypes: string[];
  /** True while the debounced content search is in flight. */
  searching?: boolean;
  resultCount: number;
  totalCount: number;
  show?: { audience?: boolean; status?: boolean; scope?: boolean; combined?: boolean };
  searchPlaceholder?: string;
  /** Put the select row behind a "More filters" disclosure, leaving search and
   *  the type chips — the two controls reached for constantly — always
   *  visible. Opt-in rather than the default so the athlete's My Reports keeps
   *  the bar it has; that surface already hides three of the four selects, and
   *  collapsing the one that remains would put a disclosure in front of a
   *  single sort control.
   *
   *  A hidden control that is doing something is the one real hazard here, so
   *  the toggle carries a count of the filters folded away and stays open once
   *  opened. */
  collapsible?: boolean;
}

const labelCls = "text-xs font-medium";

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="flex flex-col gap-1">
      <span className={labelCls} style={{ color: "var(--text-muted)" }}>
        {label}
      </span>
      {children}
    </label>
  );
}

export default function ReportFilterBar({
  value,
  onChange,
  availableTypes,
  searching = false,
  resultCount,
  totalCount,
  show = {},
  searchPlaceholder = "Search athlete, type, or anything in the report text…",
  collapsible = false,
}: ReportFilterBarProps) {
  const showAudience = show.audience ?? true;
  const showStatus = show.status ?? true;
  const showScope = show.scope ?? true;
  const showCombined = show.combined ?? true;

  const [open, setOpen] = useState(false);

  // Counted from what is actually rendered, not from the whole filter state: a
  // surface with `scope` turned off can never have an active author filter, and
  // badging one would be a count of something the reader cannot see or clear.
  const hiddenActive =
    (showAudience && value.audience !== "all" ? 1 : 0) +
    (showStatus && value.status !== "all" ? 1 : 0) +
    (showScope && value.scope !== "all" ? 1 : 0) +
    // Sort lives in the same drawer and is equally invisible when closed.
    // It reorders rather than removes, but "why is this list oldest-first"
    // is the same lost minute as a filter you forgot you set.
    (value.sort !== "date_desc" ? 1 : 0);

  const set = <K extends keyof ReportFilterState>(key: K, v: ReportFilterState[K]) =>
    onChange({ ...value, [key]: v });

  const toggleType = (t: string) =>
    set("types", value.types.includes(t) ? value.types.filter((x) => x !== t) : [...value.types, t]);

  const active = hasActiveReportFilters(value);

  return (
    <div
      className={`flex flex-col gap-4 ${CARD} p-4`}
      style={{ borderColor: "var(--border)", backgroundColor: "var(--surface)" }}
    >
      <div className="relative">
        <Search
          size={15}
          aria-hidden="true"
          className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2"
          style={{ color: "var(--text-muted)" }}
        />
        <input
          type="search"
          value={value.query}
          onChange={(e) => set("query", e.target.value)}
          placeholder={searchPlaceholder}
          aria-label="Search reports"
          className={`${INPUT} pl-9`}
          style={INPUT_STYLE}
        />
      </div>

      {/* Type chips. Multi-select, CONTAINS semantics — a combined report
          matches every domain it contains. See lib/reportSearch.ts. */}
      {(availableTypes.length > 0 || collapsible) && (
        <div className="flex flex-wrap items-center gap-2">
          {availableTypes.length > 0 && (
          <span className={labelCls} style={{ color: "var(--text-muted)" }}>
            Type
          </span>
          )}
          {availableTypes.map((t) => {
            const on = value.types.includes(t);
            return (
              <button
                key={t}
                type="button"
                onClick={() => toggleType(t)}
                aria-pressed={on}
                className={`${CHIP} transition-colors duration-150`}
                style={{
                  backgroundColor: on ? "color-mix(in srgb, var(--brand-blue) 14%, transparent)" : "var(--bg)",
                  color: on ? "var(--brand-blue)" : "var(--text)",
                  border: `1px solid ${on ? "var(--brand-blue)" : "var(--border)"}`,
                }}
              >
                {REPORT_TYPE_LABELS[t] ?? t}
              </button>
            );
          })}
          {showCombined && (
            <button
              type="button"
              onClick={() => set("combinedOnly", !value.combinedOnly)}
              aria-pressed={value.combinedOnly}
              title="Only reports covering more than one domain in a single document"
              className={`${CHIP} transition-colors duration-150`}
              style={{
                backgroundColor: value.combinedOnly
                  ? "color-mix(in srgb, var(--brand-teal) 14%, transparent)"
                  : "var(--bg)",
                color: value.combinedOnly ? "var(--brand-teal)" : "var(--text-muted)",
                border: `1px solid ${value.combinedOnly ? "var(--brand-teal)" : "var(--border)"}`,
              }}
            >
              Combined only
            </button>
          )}

          {collapsible && (
            <button
              type="button"
              onClick={() => setOpen((v) => !v)}
              aria-expanded={open}
              aria-controls="report-filter-drawer"
              className={`${CHIP} ml-auto inline-flex items-center gap-1.5 transition-colors duration-150`}
              style={{
                backgroundColor: "var(--bg)",
                color: hiddenActive > 0 ? "var(--brand-blue)" : "var(--text-muted)",
                border: `1px solid ${hiddenActive > 0 ? "var(--brand-blue)" : "var(--border)"}`,
              }}
            >
              <SlidersHorizontal size={12} aria-hidden="true" />
              {open ? "Hide filters" : "More filters"}
              {/* Only while closed: once the drawer is open the controls speak
                  for themselves, and a count sitting above them reads as a
                  second, separate thing to go and find. */}
              {!open && hiddenActive > 0 && (
                <span
                  className="rounded-full px-1.5 font-medium"
                  style={{ backgroundColor: "color-mix(in srgb, var(--brand-blue) 18%, transparent)" }}
                >
                  {hiddenActive}
                </span>
              )}
            </button>
          )}
        </div>
      )}

      {/* Class rather than the `hidden` ATTRIBUTE: the attribute's display:none
          comes from the UA stylesheet, which any author-level `display:flex`
          outranks — so `hidden` on a `flex` element does nothing at all. The
          element stays mounted either way, which keeps aria-controls pointing
          at something real and preserves each select's state across a
          close/open. */}
      <div
        id="report-filter-drawer"
        className={collapsible && !open ? "hidden" : "flex flex-wrap items-end gap-3"}
      >
        {showAudience && (
          <Field label="Audience">
            <select
              value={value.audience}
              onChange={(e) => set("audience", e.target.value as ReportFilterState["audience"])}
              className={INPUT}
              style={{ ...INPUT_STYLE, paddingTop: ".375rem", paddingBottom: ".375rem" }}
            >
              {REPORT_AUDIENCE_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>
                  {o.label}
                </option>
              ))}
            </select>
          </Field>
        )}

        {showStatus && (
          <Field label="Status">
            <select
              value={value.status}
              onChange={(e) => set("status", e.target.value as ReportFilterState["status"])}
              className={INPUT}
              style={{ ...INPUT_STYLE, paddingTop: ".375rem", paddingBottom: ".375rem" }}
            >
              {REPORT_STATUS_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>
                  {o.label}
                </option>
              ))}
            </select>
          </Field>
        )}

        {showScope && (
          <Field label="Author">
            <select
              value={value.scope}
              onChange={(e) => set("scope", e.target.value as ReportFilterState["scope"])}
              className={INPUT}
              style={{ ...INPUT_STYLE, paddingTop: ".375rem", paddingBottom: ".375rem" }}
            >
              {REPORT_SCOPE_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>
                  {o.label}
                </option>
              ))}
            </select>
          </Field>
        )}

        <Field label="Sort by">
          <select
            value={value.sort}
            onChange={(e) => set("sort", e.target.value as ReportFilterState["sort"])}
            className={INPUT}
            style={{ ...INPUT_STYLE, paddingTop: ".375rem", paddingBottom: ".375rem" }}
          >
            {REPORT_SORT_OPTIONS.map((o) => (
              <option key={o.value} value={o.value}>
                {o.label}
              </option>
            ))}
          </select>
        </Field>
      </div>

      <div className="flex flex-wrap items-center justify-between gap-2">
        <p role="status" aria-live="polite" className="text-xs" style={{ color: "var(--text-muted)" }}>
          Showing {resultCount} of {totalCount} report{totalCount === 1 ? "" : "s"}
          {/* Announced, not just decorative: without it a content match that
              arrives after the metadata results looks like the list changing
              on its own. */}
          {searching && " · searching report text…"}
        </p>
        {active && (
          <button
            type="button"
            onClick={() =>
              onChange({ ...value, query: "", types: [], combinedOnly: false, audience: "all", status: "all", scope: "all" })
            }
            className={`${BTN_TERTIARY} inline-flex items-center gap-1 !px-2 !py-1`}
            style={{ color: "var(--text-muted)" }}
          >
            <X size={13} aria-hidden="true" />
            Clear filters
          </button>
        )}
      </div>
    </div>
  );
}
