"use client";

import { Search, X } from "lucide-react";
import { REPORT_TYPE_LABELS } from "@/lib/constants";
import {
  REPORT_SORT_OPTIONS,
  REPORT_AUDIENCE_OPTIONS,
  REPORT_STATUS_OPTIONS,
  REPORT_SCOPE_OPTIONS,
  hasActiveReportFilters,
  type ReportFilterState,
} from "@/lib/reportSearch";
import { BTN_TERTIARY, CARD, CHIP, INPUT, INPUT_STYLE } from "@/lib/ui";

// The controls above Report History. Fully controlled — it owns no state, so
// the same bar drives the practitioner history and the athlete's My Reports,
// which need different subsets of it.
//
// `show` turns off the controls a surface has no use for rather than forcing
// each caller to reimplement the bar. On My Reports, "audience", "status" and
// "scope" are all meaningless: an athlete only ever sees reports someone
// deliberately shared with them, so every row would be shared/official and none
// of them was generated by the reader.

export interface ReportFilterBarProps {
  value: ReportFilterState;
  onChange: (next: ReportFilterState) => void;
  /** Types present in the underlying data, so the chips only offer filters that
   *  can actually match something. */
  availableTypes: string[];
  /** True while the debounced content search is in flight. */
  searching?: boolean;
  resultCount: number;
  totalCount: number;
  show?: { audience?: boolean; status?: boolean; scope?: boolean; combined?: boolean };
  searchPlaceholder?: string;
}

const labelCls = "text-xs font-medium";

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="flex flex-col gap-1">
      <span className={labelCls} style={{ color: "var(--text-muted)" }}>
        {label}
      </span>
      {children}
    </label>
  );
}

export default function ReportFilterBar({
  value,
  onChange,
  availableTypes,
  searching = false,
  resultCount,
  totalCount,
  show = {},
  searchPlaceholder = "Search athlete, type, or anything in the report text…",
}: ReportFilterBarProps) {
  const showAudience = show.audience ?? true;
  const showStatus = show.status ?? true;
  const showScope = show.scope ?? true;
  const showCombined = show.combined ?? true;

  const set = <K extends keyof ReportFilterState>(key: K, v: ReportFilterState[K]) =>
    onChange({ ...value, [key]: v });

  const toggleType = (t: string) =>
    set("types", value.types.includes(t) ? value.types.filter((x) => x !== t) : [...value.types, t]);

  const active = hasActiveReportFilters(value);

  return (
    <div
      className={`flex flex-col gap-4 ${CARD} p-4`}
      style={{ borderColor: "var(--border)", backgroundColor: "var(--surface)" }}
    >
      <div className="relative">
        <Search
          size={15}
          aria-hidden="true"
          className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2"
          style={{ color: "var(--text-muted)" }}
        />
        <input
          type="search"
          value={value.query}
          onChange={(e) => set("query", e.target.value)}
          placeholder={searchPlaceholder}
          aria-label="Search reports"
          className={`${INPUT} pl-9`}
          style={INPUT_STYLE}
        />
      </div>

      {/* Type chips. Multi-select, CONTAINS semantics — a combined report
          matches every domain it contains. See lib/reportSearch.ts. */}
      {availableTypes.length > 0 && (
        <div className="flex flex-wrap items-center gap-2">
          <span className={labelCls} style={{ color: "var(--text-muted)" }}>
            Type
          </span>
          {availableTypes.map((t) => {
            const on = value.types.includes(t);
            return (
              <button
                key={t}
                type="button"
                onClick={() => toggleType(t)}
                aria-pressed={on}
                className={`${CHIP} transition-colors duration-150`}
                style={{
                  backgroundColor: on ? "color-mix(in srgb, var(--brand-blue) 14%, transparent)" : "var(--bg)",
                  color: on ? "var(--brand-blue)" : "var(--text)",
                  border: `1px solid ${on ? "var(--brand-blue)" : "var(--border)"}`,
                }}
              >
                {REPORT_TYPE_LABELS[t] ?? t}
              </button>
            );
          })}
          {showCombined && (
            <button
              type="button"
              onClick={() => set("combinedOnly", !value.combinedOnly)}
              aria-pressed={value.combinedOnly}
              title="Only reports covering more than one domain in a single document"
              className={`${CHIP} transition-colors duration-150`}
              style={{
                backgroundColor: value.combinedOnly
                  ? "color-mix(in srgb, var(--brand-teal) 14%, transparent)"
                  : "var(--bg)",
                color: value.combinedOnly ? "var(--brand-teal)" : "var(--text-muted)",
                border: `1px solid ${value.combinedOnly ? "var(--brand-teal)" : "var(--border)"}`,
              }}
            >
              Combined only
            </button>
          )}
        </div>
      )}

      <div className="flex flex-wrap items-end gap-3">
        {showAudience && (
          <Field label="Audience">
            <select
              value={value.audience}
              onChange={(e) => set("audience", e.target.value as ReportFilterState["audience"])}
              className={INPUT}
              style={{ ...INPUT_STYLE, paddingTop: ".375rem", paddingBottom: ".375rem" }}
            >
              {REPORT_AUDIENCE_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>
                  {o.label}
                </option>
              ))}
            </select>
          </Field>
        )}

        {showStatus && (
          <Field label="Status">
            <select
              value={value.status}
              onChange={(e) => set("status", e.target.value as ReportFilterState["status"])}
              className={INPUT}
              style={{ ...INPUT_STYLE, paddingTop: ".375rem", paddingBottom: ".375rem" }}
            >
              {REPORT_STATUS_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>
                  {o.label}
                </option>
              ))}
            </select>
          </Field>
        )}

        {showScope && (
          <Field label="Author">
            <select
              value={value.scope}
              onChange={(e) => set("scope", e.target.value as ReportFilterState["scope"])}
              className={INPUT}
              style={{ ...INPUT_STYLE, paddingTop: ".375rem", paddingBottom: ".375rem" }}
            >
              {REPORT_SCOPE_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>
                  {o.label}
                </option>
              ))}
            </select>
          </Field>
        )}

        <Field label="Sort by">
          <select
            value={value.sort}
            onChange={(e) => set("sort", e.target.value as ReportFilterState["sort"])}
            className={INPUT}
            style={{ ...INPUT_STYLE, paddingTop: ".375rem", paddingBottom: ".375rem" }}
          >
            {REPORT_SORT_OPTIONS.map((o) => (
              <option key={o.value} value={o.value}>
                {o.label}
              </option>
            ))}
          </select>
        </Field>
      </div>

      <div className="flex flex-wrap items-center justify-between gap-2">
        <p role="status" aria-live="polite" className="text-xs" style={{ color: "var(--text-muted)" }}>
          Showing {resultCount} of {totalCount} report{totalCount === 1 ? "" : "s"}
          {/* Announced, not just decorative: without it a content match that
              arrives after the metadata results looks like the list changing
              on its own. */}
          {searching && " · searching report text…"}
        </p>
        {active && (
          <button
            type="button"
            onClick={() =>
              onChange({ ...value, query: "", types: [], combinedOnly: false, audience: "all", status: "all", scope: "all" })
            }
            className={`${BTN_TERTIARY} inline-flex items-center gap-1 !px-2 !py-1`}
            style={{ color: "var(--text-muted)" }}
          >
            <X size={13} aria-hidden="true" />
            Clear filters
          </button>
        )}
      </div>
    </div>
  );
}
