"use client";

import { useMemo, useState } from "react";
import ShareReportPanel, { type RecipientCandidate } from "./ShareReportPanel";
import ReportPdfLink from "@/components/ReportPdfLink";
import ReportSummaryBody from "@/components/ReportSummaryBody";
import ReportFilterBar from "@/components/ReportFilterBar";
import { useReportSearch } from "@/lib/useReportSearch";
import { reportTypeLabel, type ReportListItem } from "@/lib/reportSearch";
import { BADGE, CARD, CHIP } from "@/lib/ui";

// Practitioner-facing Report History.
//
// Two things changed here beyond the controls themselves, both forced by real
// numbers rather than taste (measured: mean ai_summary ~10KB across 56 real
// reports):
//
//  1. `reports` no longer carries `summary`. The list is metadata only and the
//     prose is fetched on expand — see components/ReportSummaryBody.tsx.
//  2. Search has two halves. Athlete name / type / author match locally and
//     instantly; report TEXT is matched server-side under the caller's own
//     session, because the text is no longer in the browser.
//
// Neither half is an access boundary: `reports` arrives already scoped by RLS,
// and the content search returns ids from an equally scoped query. See the
// notes in lib/reportSearch.ts and app/actions/reportSearch.ts.

export type { ReportListItem as ReportHistoryEntry };

function ReportRow({
  teamId,
  report,
  practitioners,
}: {
  teamId: string;
  report: ReportListItem;
  practitioners: RecipientCandidate[];
}) {
  const [expanded, setExpanded] = useState(false);
  const typeLabel = reportTypeLabel(report.reportTypes);
  const recipients: RecipientCandidate[] = report.athleteId
    ? [{ id: report.athleteId, label: `${report.athleteName} (athlete)` }, ...practitioners]
    : practitioners;

  return (
    <div className="flex flex-col gap-3 border-b py-4 last:border-b-0" style={{ borderColor: "var(--border)" }}>
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <p className="text-sm font-medium" style={{ color: "var(--text)" }}>
            {typeLabel} — {report.athleteName}
          </p>
          <p className="text-xs" style={{ color: "var(--text-muted)" }}>
            {report.periodStart} to {report.periodEnd} · generated by {report.generatedByName} ·{" "}
            {String(report.createdAt).slice(0, 10)}
          </p>
        </div>
        <div className="flex items-center gap-3">
          {/* Audience is what the document was WRITTEN for and changes its
              register (lib/reportAudience.ts) — worth showing now that it is
              filterable, so a filtered list explains itself. */}
          <span
            className={CHIP}
            style={{ backgroundColor: "var(--bg)", color: "var(--text-muted)", border: "1px solid var(--border)" }}
          >
            {report.audience === "athlete" ? "For athlete" : "For practitioner"}
          </span>
          {report.hasPdf && <ReportPdfLink reportId={report.id} />}
          {report.isOfficial && (
            <span
              className={BADGE}
              style={{ backgroundColor: "color-mix(in srgb, var(--success) 12%, transparent)", color: "var(--success)" }}
            >
              Official
            </span>
          )}
          <button
            type="button"
            onClick={() => setExpanded((v) => !v)}
            aria-expanded={expanded}
            className="text-xs font-medium underline-offset-2 hover:underline"
            style={{ color: "var(--brand-blue)" }}
          >
            {expanded ? "Hide report" : "View report"}
          </button>
        </div>
      </div>

      {expanded && <ReportSummaryBody reportId={report.id} />}

      {report.isOwnReport ? (
        <ShareReportPanel
          teamId={teamId}
          reportId={report.id}
          recipients={recipients}
          alreadySharedWith={report.sharedWith}
        />
      ) : (
        <div className="flex flex-wrap items-center gap-2 text-xs" style={{ color: "var(--text-muted)" }}>
          <span className="font-medium" style={{ color: "var(--text)" }}>
            Shared with:
          </span>
          {report.sharedWith.length > 0
            ? recipients
                .filter((r) => report.sharedWith.includes(r.id))
                .map((r) => (
                  <span
                    key={r.id}
                    className={CHIP}
                    style={{ backgroundColor: "var(--bg)", border: "1px solid var(--border)" }}
                  >
                    {r.label}
                  </span>
                ))
            : "no one yet"}
        </div>
      )}
    </div>
  );
}

export default function ReportHistory({
  teamId,
  reports,
  practitioners,
}: {
  teamId: string;
  reports: ReportListItem[];
  athletes: { id: string; first_name: string; last_name: string; code: string }[];
  practitioners: RecipientCandidate[];
}) {
  const { filters, setFilters, visible, searching } = useReportSearch(reports, { teamId });

  // Only offer chips for types actually present, so the bar never advertises a
  // filter that can only ever return nothing. Combined reports contribute each
  // of their domains, matching the CONTAINS filter semantics.
  const availableTypes = useMemo(() => {
    const seen = new Set<string>();
    for (const r of reports) for (const t of r.reportTypes) seen.add(t);
    return [...seen].sort();
  }, [reports]);

  if (reports.length === 0) {
    return (
      <div className={`${CARD} p-10 text-center`} style={{ borderColor: "var(--border)", backgroundColor: "var(--surface)" }}>
        <p style={{ color: "var(--text-muted)" }}>No reports generated for this team yet.</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      <ReportFilterBar
        value={filters}
        onChange={setFilters}
        availableTypes={availableTypes}
        searching={searching}
        resultCount={visible.length}
        totalCount={reports.length}
      />

      {visible.length === 0 ? (
        <div className={`${CARD} p-10 text-center`} style={{ borderColor: "var(--border)", backgroundColor: "var(--surface)" }}>
          <p style={{ color: "var(--text-muted)" }}>No reports match these filters.</p>
        </div>
      ) : (
        <div className={`${CARD} px-6`} style={{ borderColor: "var(--border)", backgroundColor: "var(--surface)" }}>
          {visible.map((report) => (
            <ReportRow key={report.id} teamId={teamId} report={report} practitioners={practitioners} />
          ))}
        </div>
      )}
    </div>
  );
}
