"use client";

import { useState } from "react";
import { REPORT_TYPE_LABELS } from "@/lib/constants";
import ShareReportPanel, { type RecipientCandidate } from "./ShareReportPanel";
import ReportMarkdown from "@/components/ReportMarkdown";
import ReportPdfLink from "@/components/ReportPdfLink";
import { BADGE, CARD, CHIP, PANEL } from "@/lib/ui";

export interface ReportHistoryEntry {
  id: string;
  reportTypes: string[];
  athleteId: string | null;
  athleteName: string;
  periodStart: string | null;
  periodEnd: string | null;
  isOfficial: boolean;
  sharedWith: string[];
  generatedByName: string;
  isOwnReport: boolean;
  summary: string | null;
  createdAt: string;
  hasPdf: boolean;
}

function ReportRow({
  teamId,
  report,
  practitioners,
}: {
  teamId: string;
  report: ReportHistoryEntry;
  practitioners: RecipientCandidate[];
}) {
  const [expanded, setExpanded] = useState(false);
  const typeLabel = report.reportTypes.map((t) => REPORT_TYPE_LABELS[t] ?? t).join(" + ");
  const recipients: RecipientCandidate[] = report.athleteId
    ? [{ id: report.athleteId, label: `${report.athleteName} (athlete)` }, ...practitioners]
    : practitioners;

  return (
    <div className="flex flex-col gap-3 border-b py-4 last:border-b-0" style={{ borderColor: "var(--border)" }}>
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <p className="text-sm font-medium" style={{ color: "var(--text)" }}>
            {typeLabel} — {report.athleteName}
          </p>
          <p className="text-xs" style={{ color: "var(--text-muted)" }}>
            {report.periodStart} to {report.periodEnd} · generated by {report.generatedByName} ·{" "}
            {new Date(report.createdAt).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}
          </p>
        </div>
        <div className="flex items-center gap-3">
          {report.hasPdf && <ReportPdfLink reportId={report.id} />}
          {report.isOfficial && (
            <span
              className={BADGE}
              style={{ backgroundColor: "color-mix(in srgb, var(--success) 12%, transparent)", color: "var(--success)" }}
            >
              Official
            </span>
          )}
          <button
            type="button"
            onClick={() => setExpanded((v) => !v)}
            className="text-xs font-medium underline-offset-2 hover:underline"
            style={{ color: "var(--brand-blue)" }}
          >
            {expanded ? "Hide report" : "View report"}
          </button>
        </div>
      </div>

      {expanded && report.summary && (
        <ReportMarkdown
          className={`${PANEL} p-4`}
          style={{ borderColor: "var(--border)", backgroundColor: "var(--bg)", color: "var(--text)" }}
        >
          {report.summary}
        </ReportMarkdown>
      )}

      {report.isOwnReport ? (
        <ShareReportPanel
          teamId={teamId}
          reportId={report.id}
          recipients={recipients}
          alreadySharedWith={report.sharedWith}
        />
      ) : (
        <div className="flex flex-wrap items-center gap-2 text-xs" style={{ color: "var(--text-muted)" }}>
          <span className="font-medium" style={{ color: "var(--text)" }}>
            Shared with:
          </span>
          {report.sharedWith.length > 0
            ? recipients
                .filter((r) => report.sharedWith.includes(r.id))
                .map((r) => (
                  <span
                    key={r.id}
                    className={CHIP}
                    style={{ backgroundColor: "var(--bg)", border: "1px solid var(--border)" }}
                  >
                    {r.label}
                  </span>
                ))
            : "no one yet"}
        </div>
      )}
    </div>
  );
}

export default function ReportHistory({
  teamId,
  reports,
  practitioners,
}: {
  teamId: string;
  reports: ReportHistoryEntry[];
  athletes: { id: string; first_name: string; last_name: string; code: string }[];
  practitioners: RecipientCandidate[];
}) {
  if (reports.length === 0) {
    return (
      <div
        className={`${CARD} p-10 text-center`}
        style={{ borderColor: "var(--border)", backgroundColor: "var(--surface)" }}
      >
        <p style={{ color: "var(--text-muted)" }}>No reports generated for this team yet.</p>
      </div>
    );
  }

  return (
    <div
      className={`${CARD} px-6`}
      style={{ borderColor: "var(--border)", backgroundColor: "var(--surface)" }}
    >
      {reports.map((report) => (
        <ReportRow key={report.id} teamId={teamId} report={report} practitioners={practitioners} />
      ))}
    </div>
  );
}
