"use client";

import { useMemo, useState } from "react";
import ReportPdfLink from "@/components/ReportPdfLink";
import ReportSummaryBody from "@/components/ReportSummaryBody";
import ReportFilterBar from "@/components/ReportFilterBar";
import { useReportSearch } from "@/lib/useReportSearch";
import { reportTypeLabel, type ReportListItem } from "@/lib/reportSearch";
import { CARD } from "@/lib/ui";

// The athlete's My Reports, sharing the search/filter/sort machinery with the
// practitioner history.
//
// WHICH CONTROLS THIS SURFACE GETS, AND WHY THE OTHERS ARE OFF:
//
//   search   yes — same two halves (type label locally, report text on the
//                  server, scoped to reports shared with this reader)
//   type     yes — an athlete accumulates several domains over a season
//   sort     yes — date and type. "Athlete name" is offered by the shared bar's
//                  sort list but is inert here: every report is about the
//                  reader, so it degrades to the date tiebreak rather than
//                  reordering anything.
//   audience no  — not a distinction the athlete can act on
//   status   no  — everything they can see was, by definition, shared with them
//   author   no  — an athlete generates nothing, so "generated by me" is empty
//
// Turning those three off is a display choice, not an access one: the athlete
// could not see another audience's or another author's report either way,
// because `reports` RLS never returns it.

export type { ReportListItem as MyReportEntry };

function ReportCard({ report }: { report: ReportListItem }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className={`${CARD} p-5`} style={{ borderColor: "var(--border)", backgroundColor: "var(--surface)" }}>
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <p className="text-sm font-semibold" style={{ color: "var(--text)" }}>
            {reportTypeLabel(report.reportTypes)}
          </p>
          <p className="text-xs" style={{ color: "var(--text-muted)" }}>
            {report.periodStart} to {report.periodEnd} · shared by {report.generatedByName} ·{" "}
            {String(report.createdAt).slice(0, 10)}
          </p>
        </div>
        <div className="flex items-center gap-3">
          {report.hasPdf && <ReportPdfLink reportId={report.id} />}
          <button
            type="button"
            onClick={() => setExpanded((v) => !v)}
            aria-expanded={expanded}
            className="text-xs font-medium underline-offset-2 hover:underline"
            style={{ color: "var(--brand-blue)" }}
          >
            {expanded ? "Hide report" : "View report"}
          </button>
        </div>
      </div>

      {expanded && (
        <div className="mt-4">
          <ReportSummaryBody reportId={report.id} />
        </div>
      )}
    </div>
  );
}

export default function MyReportsList({ reports }: { reports: ReportListItem[] }) {
  const { filters, setFilters, visible, searching } = useReportSearch(reports, { sharedWithMe: true });

  const availableTypes = useMemo(() => {
    const seen = new Set<string>();
    for (const r of reports) for (const t of r.reportTypes) seen.add(t);
    return [...seen].sort();
  }, [reports]);

  // The bar is real machinery, not decoration — below a handful of reports it
  // is just clutter above a list you can read in one glance.
  const showBar = reports.length > 3;

  return (
    <div className="flex flex-col gap-4">
      {showBar && (
        <ReportFilterBar
          value={filters}
          onChange={setFilters}
          availableTypes={availableTypes}
          searching={searching}
          resultCount={visible.length}
          totalCount={reports.length}
          show={{ audience: false, status: false, scope: false, combined: true }}
          searchPlaceholder="Search your reports by type or anything in the text…"
        />
      )}

      {visible.length === 0 ? (
        <div className={`${CARD} p-10 text-center`} style={{ borderColor: "var(--border)", backgroundColor: "var(--surface)" }}>
          <p style={{ color: "var(--text-muted)" }}>No reports match these filters.</p>
        </div>
      ) : (
        visible.map((report) => <ReportCard key={report.id} report={report} />)
      )}
    </div>
  );
}
